language: python

cache:
  pip: true
  directories:
  - .tox
  - $HOME/.cache/pip

sudo: false

env:
- TOXENV=py27
- TOXENV=py33
- TOXENV=py34
- TOXENV=pypy
- TOXENV=cover

install:
- pip install tox

script: tox
